"""add_user_profile_fields

Revision ID: 45ae78cc4d80
Revises: cc16310a95b7
Create Date: 2025-10-14 23:37:06.913929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ae78cc4d80'
down_revision = 'cc16310a95b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('gender')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
