"""add nutrition goal columns to user model

Revision ID: cc16310a95b7
Revises: a137abc8f0f6
Create Date: 2025-10-05 23:06:41.184933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc16310a95b7'
down_revision = 'a137abc8f0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_calorie_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_protein_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('daily_carb_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('daily_fat_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('daily_fat_goal')
        batch_op.drop_column('daily_carb_goal')
        batch_op.drop_column('daily_protein_goal')
        batch_op.drop_column('daily_calorie_goal')

    # ### end Alembic commands ###
